project_id = "rvdlyufaeljvmnboucmr"

[functions.cleanup-half-bookings]
verify_jwt = false

[functions.create-booking]
verify_jwt = false

[functions.cancel-booking]
verify_jwt = false

[functions.notify-join]
verify_jwt = false

[functions.join-booking]
verify_jwt = false

[functions.update-booking]
verify_jwt = false
